### ISSUE TITLE
Support for non-eclipse users

### ISSUE THREAD

**Issue by spyhunter99** [openwide-java/artifact-listener#49]
Would be great to have instructions for setup and/or support for non eclipse users.

**Comment by lalmeras** [comment]
All the build is in fact handled by maven, so any IDE with maven support may be used to work on this project. And the work done in another ticket on maven-centric way to initialize and run the application and the associated documentation must be enough, I think, for non-eclipse user.

The only thing that maybe should be a problem is the use of annotation processors (with maven-processor-plugin), but as far as I know it should work with Netbeans and IntelliJ.

So I think that if documentation is modified to focus on maven setup (instead of eclipse), it should be enough to provide a better experience for non-eclipse user.
Do you have additional feedback on this subject ? Do you still encounter difficulties ?

**Comment by spyhunter99** [comment]
we're good, the suggestions from the other ticket fixed it. thanks!

**Comment by spyhunter99** [comment]
oh and netbeans works just fine
