### ISSUE TITLE
Travis build KO because of missing owsi-core dependency

### ISSUE THREAD

**Issue by marob** [openwide-java/artifact-listener#69]
See https://travis-ci.org/openwide-java/artifact-listener/builds/579820965

[Open Wide Nexus repository](https://projects.openwide.fr/services/nexus), hosting the owsi-core artifacts, is down.

In order for the build to succeed, owsi-core artifacts should be publicly hosted (on maven central?).

**Comment by lalmeras** [comment]
Hi,

You can use this public repository https://nexus.tools.kobalt.fr/repository/igloo-releases/ with version 0.11.5 (update parent and dependencies); it is compatible with 0.11.4, hosted on https://github.com/igloo-project/igloo-parent and is a part of our effort to fork and continue to maintain owsi-core (renamed igloo-project).

This can be a way to quickly fix your build.

**Comment by marob** [comment]
Hi,

Thanks for the info. That seams to be a promising solution, but your repository seams to be protected by an SSO authentication via your GitLab.

Also, may I ask why neither owsi-core nor igloo are on maven central repository? Do they fail to meet the requirements to be published on the central? Or is there an other explanation?

**Comment by lalmeras** [comment]
Please visit https://nexus.tools.kobalt.fr/nosso/ to skip sso and enable anonymous browsing. igloo-releases is public and maven access is not filtered on this repository. I'll change this default behavior.

Project is not on maven central as we prefer to focus our effort on Igloo development and do not see any immediate advantage to do it. Publishing on Maven Central may be a possibility, but is not on our short term roadmap.

**Comment by lalmeras** [comment]
I just change the sso behavior. Anonymous access is OK on first access.

**Comment by marob** [comment]
Thanks!

I encountered some difficulties:
- the `localization-properties-consistency-maven-plugin`, used in this project, is not available in your Nexus
- repositories inherited by the parent pom point to https://nexus.tools.kobalt-si.fr/ (which DNS doesn't resolve)

By:
- removing the `localization-properties-consistency-maven-plugin` (I suppose it's not essential)
- declaring the repositories in artifact-listener's pom using the same ids (`nexus-igloo-releases` and `nexus-igloo-snapshots`) and using the correct URLs (https://nexus.tools.kobalt.fr/...)

it should be able to build.

Do you have the possibility to add the `localization-properties-consistency-maven-plugin` in version 1.0.0 in your Nexus?

Also, less important, but while https://kobalt-si.fr/ redirects to https://www.kobalt.fr/, it doesn't work with sub-domains. If you could fix that, it would be great.

**Comment by lalmeras** [comment]
We are currently trying to shutdown kobalt-si -> kobalt redirections as we do not want to maintain it forever, so I prefer to provide an updated release with fixed url for this issue.

I just push a 0.11.6 with fixed repository configurations and updated jgitflow configuration (ssh configuration broken in the former one because of jsch dependency version).

For localization-properties-consistency-maven-plugin, I remove it from 0.11.6, as we do not fork and maintain this project. This plugin is optional, as its purpose is only to check that all strings are translated. I propose you can remove it from artifact-listener poms.

Hope it helps to bring back artifact listener travis job.
